string package_name
string urdf_name
string module_name
int8 module_plug_id
string parrent_module_name
int8 parrent_module_plug_id

int8 operation
int8 CONNECT = 1
int8 DISCONNECT = 2 

---

bool success