active_description_elements:
- robot_1
- robot_2
robot_1:
  ep: 0.0
  er: 0.0
  ey: 0.0
  package_name: robotic_cell_description
  parrent: robotic_cell_base
  urdf_name: robot_arm.urdf.xacro
  x: 1.2
  y: 1.3
  z: 1.4
robot_2:
  ep: 0.0
  er: 0.0
  ey: 0.0
  package_name: robotic_cell_description
  parrent: robotic_cell_base
  urdf_name: robot_arm.urdf.xacro
  x: 1.0
  y: 1.0
  z: 1.0
